### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by lwheelden56** [tfKamran/hangouts-auto-reply-bot#2]
The readme configuration instructions do not work. "Command not found"

**Comment by tfKamran** [comment]
What platform are you using this on?

**Comment by lwheelden56** [comment]
Linux, specifically Ubuntu based.

**Comment by lwheelden56** [comment]
I get a "bot is online" message, but I cannot configure anything, even in a new terminal tab.

**Comment by tfKamran** [comment]
To help debug the issue, please execute the following to get the path of your binary:

    which hangouts-auto-reply-bot

Then check if the `hangouts-auto-reply-bot-configure` exists on the same location with:

    ls "$(which hangouts-auto-reply-bot)-configure"

Let me know the results.

**Comment by tfKamran** [comment]
I just published a new version, let me know if it solves the issue.
