### ISSUE TITLE
XMPP authentication failure

### ISSUE THREAD

**Issue by SkyEngine-OSP** [tfKamran/hangouts-auto-reply-bot#3]
upon reaching the prompt where it asks for the username and password, it returns a message **"XMPP authentication failure"** and i have no idea what to do at this point onwards.

**Comment by tfKamran** [comment]
If you are sure that your credentials are correct, you might have to enable "Less Secure Apps" in your Google Account.

You can follow this guide to do the same: https://support.google.com/accounts/answer/6010255?hl=en

**Comment by tfKamran** [comment]
Did it work for you?

**Comment by angelivene** [comment]
same prob, i already switched off the less secure apps, i get XMPP authentication failure

**Comment by tfKamran** [comment]
Try clearing your configuration and setting the credentials again with:

    hangouts-auto-reply-bot-configure clear

It is highly probable that your credentials are wrong.
