### ISSUE TITLE
XMPP authentication failure

### ISSUE THREAD

**Issue by needhelpasappp** [tfKamran/hangouts-auto-reply-bot#4]
After inputting email address and password and asked for prefix, it just closed and whenever i tried to run it again it says
XMPP authentication failure

**Comment by tfKamran** [comment]
Did you enable less secure apps in your Google account?

Refer to this documentation here: https://devanswers.co/allow-less-secure-apps-access-gmail-account/

Let me know whether this solves your issue.

**Comment by needhelpasappp** [comment]
yes I enable less secure apps, It is on

**Comment by tfKamran** [comment]
You can cross-check your credentials, I just tested on my side, it seems to be working with the latest Google APIs and security.

**Comment by tfKamran** [comment]
Did it work?

**Comment by bruhbruh5** [comment]
How do you re-enter the credentials since i just keep getting 'XMPP authentication failiure' even after turning it on. Note: I entered the incoreect credentials at the start.
