### ISSUE TITLE
XMPP authentication failure

### ISSUE THREAD

**Issue by raDiIorio** [tfKamran/hangouts-auto-reply-bot#5]
I am using Windows.

I made a typo error when entering my email address and password.

Now, whenever i tried to run it again it says:
XMPP authentication failure

How do I correct my email / password ?
thanks!

**Comment by raDiIorio** [comment]
I am using Windows.  Thanks

**Comment by tfKamran** [comment]
You can delete the config file which you find here: `~/.hangouts-auto-reply-bot.json`

**Comment by raDiIorio** [comment]
Thanks!  That solved my problem.
Ralph
