### ISSUE TITLE
Config issues

### ISSUE THREAD

**Issue by raDiIorio** [tfKamran/hangouts-auto-reply-bot#6]
I have a Windows installation.

When I enter:
hangouts-auto-reply-bot-configure list

I receive the following error:
'hangouts-auto-reply-bot-configure' is not recognized as an internal or external command, operable program or batch file.

Why does it not recognize this command ?

Thanks

**Comment by tfKamran** [comment]
I just published a new version, let me know if it solves the issue.

**Comment by raDiIorio** [comment]
The new version solves the issue.  'hangouts-auto-reply-bot-configure' is now recognized.

Thanks for the quick reply!
Ralph
