### ISSUE TITLE
wont let me finish

### ISSUE THREAD

**Issue by helpple** [tfKamran/hangouts-auto-reply-bot#7]
after i put the hangouts-auto-reply-bot in it says bot is online but then it wont let me type anything else. Know how to fix this? Am i doing it wrong?

**Comment by tfKamran** [comment]
When you start `hangouts-auto-reply-bot` for the first time, it runs `hangouts-auto-reply-bot-configure` for you by default to setup the basic details.

If you want to add to the configuration, you need to run `hangouts-auto-reply-bot-configure`.

**Comment by helpple** [comment]
Ok thank you! Also how do you get it to work on hangouts?

**Comment by tfKamran** [comment]
It connects to your on Hangouts with the credentials you put in the first time you launched it, as soon as you start the bot.
